model:
  name: MobileNetV2
  pretrained: true
  num_classes: 8  # 7 disease classes + 1 healthy class

training:
  batch_size: 32
  learning_rate: 0.001
  num_epochs: 50
  weight_decay: 0.0001

data:
  train_data_path: data/train
  val_data_path: data/val
  image_size: [224, 224]

augmentation:
  random_flip: true
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]